name: realestateproperty.sg
favicon: null
layout_spectrum: 0.74129
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080307'
    - '#4f382a'
    - '#a17f66'
    - '#d5fffe'
    - '#a3c579'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.3866494186222553
  rhythmicContrast: 0.25
purpose: []
