name: realestateproperty.sg
favicon: null
layout_spectrum: 0.8899033
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070306'
    - '#4D3628'
    - '#A28066'
    - '#D6FDFD'
    - '#FBA388'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
